stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/14601930/trigger/pipeline
  only:
    - master
