stages:
  - deploy

deploy:
  stage: deploy
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.example.com/api/v4/projects/14601930/trigger/pipeline
  only:
    - master
